cleaning_config:

    cleaner:
        flags:
            correct_misspelling: True
            exclude_entity_types: True
            expand_acronyms: True
            filter_stopwords: True
            filter_language: True
            fix_fragmented_tokens: True
            include_pos_tags: True
            tag_whitelisted_entities: True
        params:
            entities:
                - CARDINAL
                - TIME
                - PERCENT
                - MONEY
            fragment